Chambers/ViewModels/StoryViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using Chambers.Models;

namespace Chambers.ViewModels
{
    public class StoryViewModel
    {
        public Character LeftArbiter { get; set; }
        public Character RightArbiter { get; set; }
        public Character LeftVictim { get; set; }
        public Character RightVictim { get; set; }

        public Affliction LeftArbiterAffliction { get; set; }
        public Affliction RightArbiterAffliction { get; set; }
        public Affliction LeftVictimAffliction { get; set; }
        public Affliction RightVictimAffliction { get; set; }

        public bool UseSelflessness { get; set; }
        public bool UseFrustation { get; set; }
    }
}

Chambers/Controllers/StoryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Chambers.Models;
using Chambers.ViewModels;

namespace Chambers.Controllers
{
    public class StoryController : Controller
    {
        // GET: Story
        public ActionResult Index()
        {
            var vm = new StoryStatusViewModel();
            return View(vm);
        }

        public ActionResult Edit(int characterAfflictionID)
        {
            var vm = new EditStageViewModel(characterAfflictionID);
            return View(vm);
        }

        [HttpPost]
        public ActionResult Edit(EditStageViewModel model)
        {
            var _db = new Entities();
            _db.UpdateCharacterAffliction(model);
            return RedirectToAction("Index");
        }

        public ActionResult Create(int characterID, int afflictionID, int stageNum)
        {
            var _db = new Entities();
            var vm = new CreateStageViewModel();
            vm.CharacterID = characterID;
            vm.CharacterName = _db.Characters.Where(c => c.CharacterId == characterID).FirstOrDefault().Name;
            vm.AfflictionID = afflictionID;
            vm.StageNum = stageNum;
            var affliction = _db.Afflictions.Where(a => a.AfflicationId == afflictionID).FirstOrDefault();
            vm.IsVictimAffliction = affliction.IsAdvancedIllness;
            vm.AfflictionName = affliction.Name;
            return View(vm);
        }

        [HttpPost]
        public ActionResult Create(CreateStageViewModel model)
        {
            var _db = new Entities();
            var affliction = _db.Afflictions.Where(a => a.AfflicationId == model.AfflictionID).FirstOrDefault();
            var character = _db.Characters.Where(c => c.CharacterId == model.CharacterID).FirstOrDefault();
            var characterAffliction = new CharacterAffliction()
            {
                AfflictionID = model.AfflictionID,
                CharacterID = model.CharacterID,
                Descriptor = model.Descriptor,
                FinaleText = model.FinaleText,
                OpponentVoteText = model.OVText,
                SelfVoteText = model.SVText,
                Stage = model.StageNum,
                ProgressionText = model.ProgressionText,
                Character = character,
                Affliction = affliction
            };
            _db.CharacterAfflictions.Add(characterAffliction);
            _db.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

Chambers/Views/Story/Create.cshtml
@model Chambers.ViewModels.CreateStageViewModel
@{
    ViewBag.Title = "Create";
}

<h2>Creating Stage @Model.StageNum of @Model.CharacterName's @Model.AfflictionName Transformation</h2>

@using (Html.BeginForm("Create", "Story", FormMethod.Post, new { data_toggle = "validator" }))
{
    @Html.HiddenFor(Model => Model.CharacterID)
    @Html.HiddenFor(m => m.AfflictionID)
    @Html.HiddenFor(m => m.StageNum)
    <div>
        <label>Descriptor</label> @Html.TextBoxFor(Model => Model.Descriptor)
    </div><br />
    <div>
        <label>ProgressionText</label><br /> @Html.TextAreaFor(Model => Model.ProgressionText, new { rows = "7", cols = "100" })
    </div><br />
    if (!Model.IsVictimAffliction)
    {
        <div>
            <label>Self Vote Text</label><br /> @Html.TextAreaFor(Model => Model.SVText, new { rows = "7", cols = "100" })
        </div><br />
        <div>
            <label>Opponent Vote Text</label><br />  @Html.TextAreaFor(Model => Model.OVText, new { rows = "7", cols = "100" })
        </div><br />
    }
    <div>
        <label>Finale Text</label><br /> @Html.TextAreaFor(Model => Model.FinaleText, new { rows = "7", cols = "100" })
    </div>
    <button type="submit">Save</button>
}

Chambers/Views/Story/Edit.cshtml
@model Chambers.ViewModels.EditStageViewModel
@{
    ViewBag.Title = "Edit";
}

<h2>Editing Stage @Model.StageNum of @Model.CharacterName's @Model.AfflictionName Transformation</h2>

@using (Html.BeginForm("Edit", "Story", FormMethod.Post, new { data_toggle = "validator" }))
{
    @Html.HiddenFor(Model => Model.CharacterAfflictionID)
    <div>
        <label>Descriptor</label> @Html.TextBoxFor(Model => Model.Descriptor)
    </div><br />
    <div>
        <label>ProgressionText</label><br /> @Html.TextAreaFor(Model => Model.ProgressionText, new { rows = "7", cols = "100" })
    </div><br/>
    if (!Model.IsVictimAffliction)
    {
    <div>
        <label>Self Vote Text</label><br /> @Html.TextAreaFor(Model => Model.SVText, new { rows = "7", cols = "100" })
    </div><br/>
    <div>
        <label>Opponent Vote Text</label><br />  @Html.TextAreaFor(Model => Model.OVText, new { rows = "7", cols = "100" })
    </div><br/>
     }
    <div>
        <label>Finale Text</label><br /> @Html.TextAreaFor(Model => Model.FinaleText, new { rows = "7", cols = "100" })
    </div>
    <button type="submit">Save</button>
 }

Chambers/Views/Story/Index.cshtml
@model Chambers.ViewModels.StoryStatusViewModel
@{
    ViewBag.Title = "Index";
}

<h4>Arbiter Afflictions</h4>
@foreach(var affliction in Model.ArbiterAfflictions)
{
    <h3>@affliction.Affliction.Name</h3>
    <table>
        <tr>
            <th>Character</th>
            <th>Stage 0</th>
            <th>Stage 1</th>
            <th>Stage 2</th>
            <th>Stage 3</th>
            <th>Stage 4</th>
            <th>Stage 5</th>
        </tr>
        @foreach(var character in affliction.CharactersWithStages)
        {
            var i = 0;
            <tr>
                <td>@character.CharacterName</td>
                @foreach(var stage in character.AfflictionStage)
                {
                    <href></href>
                    <td>@(stage.IsCompleted ? Html.ActionLink("x", "Edit", new { characterAfflictionID = stage.AfflictionStageID }) : Html.ActionLink("-", "Create", new { characterID = character.CharacterID, afflictionID = affliction.Affliction.AfflicationId, stageNum = i }))</td>
                    i++;
                }
            </tr>
        }
    </table>
}

<h4>Victim Afflictions</h4>
@foreach (var affliction in Model.VictimAfflictions)
{
    <h3>@affliction.Affliction.Name</h3>
    <table>
        <tr>
            <th>Character</th>
            <th>Stage 0</th>
            <th>Stage 1</th>
            <th>Stage 2</th>
            <th>Stage 3</th>
            <th>Stage 4</th>
            <th>Stage 5</th>
            <th>Stage 6</th>
            <th>Stage 7</th>
            <th>Stage 8</th>
            <th>Stage 9</th>
            <th>Stage 10</th>
        </tr>
        @foreach (var character in affliction.CharactersWithStages)
        {
            var i = 0;
            <tr>
                <td>@character.CharacterName</td>
                
                @foreach (var stage in character.AfflictionStage)
                {

                    <td>@(stage.IsCompleted ? Html.ActionLink("x", "Edit", new { characterAfflictionID = stage.AfflictionStageID }) : Html.ActionLink("-", "Create", new { characterID = character.CharacterID, afflictionID = affliction.Affliction.AfflicationId, stageNum = i }))</td>
                    i++;
                }
            </tr>
        }
    </table>
}